### ISSUE TITLE
Radio Music outputs constant DC offset when no audio is playing

### ISSUE THREAD

**Issue by unlessgames** [cschol/modular80#7]
Hey, love this module!

I guess the title explains it all, but here is a clip demonstrating it with mixer and scope.

https://i.imgur.com/hCGtshR.mp4

My usecase is reading a folder full of drum samples and trigger the reset from a sequencer, then modulating the station lets me easily change samples for individual hits running on the same track.

Maybe this is not how it is meant to be used in the first place, but being able to disable looping made me think otherwise.

**Comment by cschol** [comment]
I can reproduce it and will look into it. Thank you for the report.

**Comment by cschol** [comment]
Fixed in version 1.0.2.

**Comment by unlessgames** [comment]
Thank you!
