### ISSUE TITLE
station input/cv

### ISSUE THREAD

**Issue by Nowhk** [cschol/modular80#8]
hi,

shouldn't be this https://github.com/cschol/modular80/blob/master/src/RadioMusic.cpp#L648 written as

`clamp(static_cast<int>(rescale(channel, 0.0f, 1.0f, 0.0f, static_cast<float>(**objects.size() - 1**))),
			0, objects.size() - 1);`

i'm not able with external cv to manage the value. example: if I have 2 samples in the folder, i set station to 0, input 0-10cv, not able to equally select first or second. it should be 0-5 sample 1, 5-10 sample 2, correct?

thanks

**Comment by cschol** [comment]
The hardware Radio Music module has a `0-5V` range for the `Station CV` input. The VCV module follows that convention, so sample 1 would be 0-2.5, sample 2 would be 2.5-5. For 10 samples, the 10th sample would be selected from 4.5-5.

**Comment by Nowhk** [comment]
I see. Thanks! Is the code without -1 correct so?

**Comment by cschol** [comment]
Yes. The current implementation is working as expected.
